name: $(GitAssemblyInformationalVersion)


resources:
- repo: self
  clean: "true"

trigger:
  batch: true
  branches:
    include:
    - master
  paths:
    exclude:
    - docs/*
    - .readthedocs.yml

pr:
  branches:
    include:
    - '*'
  paths:
    exclude:
    - docs/*
    - .readthedocs.yml

jobs:
#- template: build.yml  
#  parameters:
#    name: macOS
#    artifactFileName: '$(Build.ArtifactStagingDirectory)/Reqnroll-macOS.zip'
#    pool:
#      name: 'Hosted macOS'

- template: build.yml  
  parameters:
    name: Windows
    artifactFileName: '$(Build.ArtifactStagingDirectory)/Reqnroll-Windows.zip'
    appInsightsInstrumentationKey: $(AppInsightsInstrumentationKey)
    pool:
      vmImage: 'windows-latest'

- template: build.yml  
  parameters:
    name: Linux
    artifactFileName: '$(Build.ArtifactStagingDirectory)/Reqnroll-Linux.zip'
    pool:
      vmImage: 'ubuntu-latest'
